---
swagger: '2.0'

################################################################################
#                              API Information                                 #
################################################################################
info:
  version: v1
  title: MathJax API
  description: |
    Blablabla
  termsOfService: http://instagram.com/about/legal/terms/api

################################################################################
#                  Host, Base Path, Schemes and Content Types                  #
################################################################################
host: localhost:8080
basePath: /
schemes:
  - http
produces:
  - application/mathml+xml
  - image/png
  - image/svg+xml
consumes:
  - application/json

################################################################################
#                                           Paths                              #
################################################################################
paths:
  /convert:
    get:
      summary: Convert a formula using MathJax
      parameters:
        - name: data
          in: body
          schema:
            type: object
            required:
              - type
              - source
            properties:
              type:
                type: string
                enum:
                  - latex
                  - mathml
              inline:
                type: boolean
                default: false
              source:
                type: string
              config:
                type: object
                default: {}
      responses:
        200:
          description: OK
